#!/usr/bin/env python3
"""
proposal-to-pdf.py — Convert Skill 04 Executive Proposal markdown to a
professionally styled PDF with McKinsey-grade formatting.

Pipeline: Markdown → HTML → CSS styling → WeasyPrint → PDF

Requires:
    pip install weasyprint markdown

Usage:
    python3 tools/proposal-to-pdf.py benchmarks/scenario-a-agribusiness/skill-04-output.md
    python3 tools/proposal-to-pdf.py skill-04-output.md -o ~/Desktop/Proposal.pdf
    python3 tools/proposal-to-pdf.py skill-04-output.md --no-cover --no-toc
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import markdown
except ImportError:
    sys.exit(
        "Error: 'markdown' package not found.\n"
        "Install with: pip install markdown"
    )

try:
    from weasyprint import HTML
except ImportError:
    sys.exit(
        "Error: 'weasyprint' package not found.\n"
        "Install with: pip install weasyprint\n"
        "macOS also requires: brew install pango cairo glib"
    )


def extract_metadata(md_text: str) -> dict:
    """Extract client name, date, classification from the markdown metadata table."""
    meta = {
        "title": "SAP S/4HANA Implementation Proposal",
        "client": "",
        "prepared_for": "",
        "date": "",
        "classification": "Confidential — Client Use Only",
        "version": "1.0",
    }

    # Try to extract from the Document Metadata table (pipe-delimited rows)
    table_pattern = re.compile(
        r"\|\s*\*\*(.+?)\*\*\s*\|\s*(.+?)\s*\|", re.MULTILINE
    )
    for match in table_pattern.finditer(md_text):
        field = match.group(1).strip().lower()
        value = match.group(2).strip()
        if "prepared for" in field:
            meta["prepared_for"] = value
        elif "company" in field:
            meta["client"] = value
        elif "date" in field and not meta["date"]:
            meta["date"] = value
        elif "classification" in field:
            meta["classification"] = value
        elif "version" in field:
            meta["version"] = value

    # Extract title from first H1
    h1_match = re.search(r"^#\s+(.+)$", md_text, re.MULTILINE)
    if h1_match:
        title = h1_match.group(1).strip()
        # Clean up: remove "Skill 04 Output:" prefix if present
        title = re.sub(r"^Skill\s+\d+\s+Output:\s*", "", title)
        # If title contains an em dash, take what's before it as the title
        if " — " in title:
            meta["title"] = title.split(" — ")[0].strip()
            if not meta["client"]:
                meta["client"] = title.split(" — ")[1].strip()
        else:
            meta["title"] = title

    return meta


def strip_internal_sections(md_text: str) -> str:
    """Remove non-client-facing sections from the markdown."""
    lines = md_text.split("\n")
    result = []
    skip = False
    skip_metadata_table = False

    for i, line in enumerate(lines):
        # Skip the H1 title line (will be on cover page)
        if line.startswith("# ") and i < 5:
            continue

        # Skip the Document Metadata section
        if re.match(r"^##\s+Document\s+Metadata", line, re.IGNORECASE):
            skip_metadata_table = True
            continue
        if skip_metadata_table:
            if line.startswith("## ") or (line.startswith("---") and i > 3):
                skip_metadata_table = False
                if line.startswith("---"):
                    continue
            else:
                continue

        # Skip Cross-Skill Consistency Verification
        if re.match(
            r"^##\s+Cross-Skill\s+Consistency", line, re.IGNORECASE
        ):
            skip = True
            continue

        # Skip end-of-document boilerplate
        if re.match(r"^\*End of Skill", line):
            skip = True
            continue
        if re.match(r"^\*Generated by SAP", line):
            skip = True
            continue
        if re.match(r"^\*Source data completeness", line):
            continue

        if skip:
            # Stop skipping when we hit a new H2 or end of file
            if line.startswith("## ") and not re.match(
                r"^##\s+Cross-Skill", line, re.IGNORECASE
            ):
                skip = False
            else:
                continue

        result.append(line)

    return "\n".join(result)


def convert_to_html(md_text: str) -> str:
    """Convert markdown to HTML with extensions."""
    extensions = ["tables", "toc", "smarty", "fenced_code"]
    extension_configs = {
        "toc": {"permalink": False, "toc_depth": "2-3"},
    }
    html = markdown.markdown(
        md_text, extensions=extensions, extension_configs=extension_configs
    )
    return html


def build_cover_page(meta: dict) -> str:
    """Generate HTML for the cover page."""
    prepared = meta.get("prepared_for", "")
    client = meta.get("client", "")
    date = meta.get("date", "")
    version = meta.get("version", "1.0")
    classification = meta.get("classification", "Confidential — Client Use Only")
    title = meta.get("title", "SAP S/4HANA Implementation Proposal")

    prepared_line = ""
    if prepared:
        prepared_line = (
            f'<div><span class="label">Prepared for</span> {prepared}</div>'
        )

    date_line = ""
    if date:
        date_line = f'<div><span class="label">Date</span> {date}</div>'

    version_line = ""
    if version:
        version_line = (
            f'<div><span class="label">Version</span> {version}</div>'
        )

    return f"""
    <div class="cover-page">
        <div class="cover-accent"></div>
        <h1>{title}</h1>
        <div class="cover-subtitle">{client}</div>
        <div class="cover-meta">
            {prepared_line}
            {date_line}
            {version_line}
        </div>
        <div class="cover-confidential">
            {classification}
        </div>
    </div>
    """


def build_toc(body_html: str) -> str:
    """Generate table of contents from H2 elements in the body HTML."""
    # Find all h2 elements with their IDs and text
    h2_pattern = re.compile(r'<h2[^>]*id="([^"]*)"[^>]*>(.*?)</h2>', re.DOTALL)
    entries = []

    for match in h2_pattern.finditer(body_html):
        section_id = match.group(1)
        # Strip HTML tags from the header text
        text = re.sub(r"<[^>]+>", "", match.group(2)).strip()
        entries.append((section_id, text))

    if not entries:
        # Fallback: try h2 without IDs
        h2_plain = re.compile(r"<h2[^>]*>(.*?)</h2>", re.DOTALL)
        for i, match in enumerate(h2_plain.finditer(body_html)):
            text = re.sub(r"<[^>]+>", "", match.group(1)).strip()
            section_id = f"section-{i}"
            entries.append((section_id, text))

    if not entries:
        return ""

    items = "\n".join(
        f'        <li><a href="#{eid}">{text}</a></li>'
        for eid, text in entries
    )

    return f"""
    <div class="toc">
        <h2>Contents</h2>
        <ul class="toc-list">
{items}
        </ul>
    </div>
    """


def ensure_h2_ids(html: str) -> str:
    """Ensure all H2 elements have id attributes for TOC linking."""
    counter = 0

    def add_id(match):
        nonlocal counter
        tag = match.group(0)
        if 'id="' in tag:
            return tag
        text = re.sub(r"<[^>]+>", "", match.group(1)).strip()
        slug = re.sub(r"[^\w\s-]", "", text.lower())
        slug = re.sub(r"[\s]+", "-", slug).strip("-")
        if not slug:
            slug = f"section-{counter}"
        counter += 1
        return f'<h2 id="{slug}">{match.group(1)}</h2>'

    return re.sub(r"<h2[^>]*>(.*?)</h2>", add_id, html, flags=re.DOTALL)


def assemble_document(
    cover_html: str, toc_html: str, body_html: str, css_path: str
) -> str:
    """Combine all parts into a complete HTML document."""
    css_content = Path(css_path).read_text(encoding="utf-8")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
{css_content}
    </style>
</head>
<body>
    {cover_html}
    {toc_html}
    <div class="content">
        {body_html}
    </div>
</body>
</html>"""


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Convert Skill 04 Executive Proposal markdown "
            "to a professionally styled PDF."
        )
    )
    parser.add_argument("input", help="Path to Skill 04 markdown output file")
    parser.add_argument(
        "--output",
        "-o",
        help="Output PDF path (default: same name with .pdf extension)",
    )
    parser.add_argument(
        "--style",
        "-s",
        help="Path to CSS stylesheet (default: tools/proposal-style.css)",
    )
    parser.add_argument("--no-cover", action="store_true", help="Skip cover page")
    parser.add_argument(
        "--no-toc", action="store_true", help="Skip table of contents"
    )
    parser.add_argument("--client", help="Override client name for cover page")
    parser.add_argument("--date", help="Override date for cover page")
    parser.add_argument("--title", help="Override document title")
    return parser.parse_args()


def main():
    args = parse_args()

    # Resolve input path
    input_path = Path(args.input).resolve()
    if not input_path.exists():
        sys.exit(f"Error: Input file not found: {input_path}")

    # Resolve CSS path
    if args.style:
        css_path = Path(args.style).resolve()
    else:
        # Default: look for proposal-style.css next to this script
        css_path = Path(__file__).parent / "proposal-style.css"
    if not css_path.exists():
        sys.exit(f"Error: CSS file not found: {css_path}")

    # Resolve output path
    if args.output:
        output_path = Path(args.output).resolve()
    else:
        output_path = input_path.with_suffix(".pdf")

    # Read markdown
    md_text = input_path.read_text(encoding="utf-8")

    # Extract metadata
    meta = extract_metadata(md_text)
    if args.client:
        meta["client"] = args.client
    if args.date:
        meta["date"] = args.date
    if args.title:
        meta["title"] = args.title

    # Strip internal sections
    proposal_md = strip_internal_sections(md_text)

    # Convert to HTML
    body_html = convert_to_html(proposal_md)

    # Ensure H2s have IDs
    body_html = ensure_h2_ids(body_html)

    # Build cover page
    cover_html = "" if args.no_cover else build_cover_page(meta)

    # Build TOC
    toc_html = "" if args.no_toc else build_toc(body_html)

    # Assemble full document
    full_html = assemble_document(cover_html, toc_html, body_html, str(css_path))

    # Generate PDF
    HTML(string=full_html).write_pdf(str(output_path))

    print(f"PDF generated: {output_path}")
    print(f"  Source: {input_path.name}")
    print(f"  Client: {meta.get('client', 'N/A')}")
    print(f"  Pages: see output file")


if __name__ == "__main__":
    main()
